### ISSUE TITLE
Can't Compile 1.0.0-pre2

### ISSUE THREAD

**Issue by claybrooks** [ooonush/FishyUnityTransport#15]
Upgraded from <1.0.0, gettting the following compilation errors:

- Library\PackageCache\com.alven.fishnet.unitytransport@38158988ea\FishyUnityTransport.DriverConstructor.cs(155,39): error CS0246: **The type or namespace name 'Exception' could not be found** (are you missing a using directive or an assembly reference?)
- Library\PackageCache\com.alven.fishnet.unitytransport@38158988ea\FishyUnityTransport.DriverConstructor.cs(158,43): error CS1061: **'NetworkSettings' does not contain a definition for 'WithSecureServerParameters' and no accessible extension method 'WithSecureServerParameters' accepting a first argument of type 'NetworkSettings' could be found** (are you missing a using directive or an assembly reference?)
- Library\PackageCache\com.alven.fishnet.unitytransport@38158988ea\FishyUnityTransport.DriverConstructor.cs(164,39): **error CS0246: The type or namespace name 'Exception' could not be found** (are you missing a using directive or an assembly reference?)
- Library\PackageCache\com.alven.fishnet.unitytransport@38158988ea\FishyUnityTransport.DriverConstructor.cs(168,47): error CS1061: **'NetworkSettings' does not contain a definition for 'WithSecureClientParameters' and no accessible extension method 'WithSecureClientParameters' accepting a first argument of type 'NetworkSettings' could be found** (are you missing a using directive or an assembly reference?)
- Library\PackageCache\com.alven.fishnet.unitytransport@38158988ea\FishyUnityTransport.DriverConstructor.cs(172,47): error CS1061: **'NetworkSettings' does not contain a definition for 'WithSecureClientParameters' and no accessible extension method 'WithSecureClientParameters' accepting a first argument of type 'NetworkSettings' could be found** (are you missing a using directive or an assembly reference?)

I blew away the previous version, wiped my Library folder and re-installed 1.0.0-pre2, still getting these compilation errors.

**Comment by ooonush** [comment]
Could you tell me what version of unity and version of UnityTransport you are using?

**Comment by claybrooks** [comment]
Unity 2023.1.6f1.  Unity Transport 2.0.2

**Comment by ooonush** [comment]
Resolved in 1.0.0-pre.3
