### ISSUE TITLE
[FIXED IN 1.0.0pre5] 1.0.0.pre3 didn't fix the issue of big payloads for me

### ISSUE THREAD

**Issue by DanielSnd** [ooonush/FishyUnityTransport#16]
[FishnetUtpIssueRepro_103pre.zip](https://github.com/ooonush/FishyUnityTransport/files/12368932/FishnetUtpIssueRepro_103pre.zip)

New Big Payload repro attached with the 103pre update. The issue persists exactly the same for me. Once I send the payload at 3000 it "clogs" and is unable to do anything else.

**Comment by ooonush** [comment]
Check version 1.0.0-pre.5 please.

**Comment by DanielSnd** [comment]
> Check version 1.0.0-pre.5 please.

It is fixed in 1.0.0-pre.5! good job ^^
