### ISSUE TITLE
KeyNotFound Exception when trying to get the client NetworkConnection

### ISSUE THREAD

**Issue by Charley3d** [ooonush/FishyUnityTransport#17]
Error when getting Client's NetworkConnection. 
This issue does not appear on the host.

Step to reproduce:
- Create an Empty object
- Add a `NetworkBehaviour` script on it
- Type following code
```csharp
public override void OnStartClient()
{
// Won't work
    print(LocalConnection);
}
```
- This error will be thrown
![image](https://github.com/ooonush/FishyUnityTransport/assets/140595165/2fd36cb0-b2b3-48ee-92a9-76a3600b5b82)

Alven already spot the issue, it's coming from the serialization of NetworkConnection. The simplest workaround is to not direclty use the NetworkConnection object, but one of its properties.

```csharp
public override void OnStartClient()
{
// Will work
    print(LocalConnection.ClientId);
}
```

I just added the issue here to help you keep a track of it =)

Link of the discussion: https://discord.com/channels/424284635074134018/1034477094731784302/1144259440233681066

**Comment by ooonush** [comment]
Resolved in 1.0.0-pre.4
