### ISSUE TITLE
Creating a Host sometimes fails.

### ISSUE THREAD

**Issue by zalkanorr** [ooonush/FishyUnityTransport#3]
Hey,
first of all thanks alot for your work, the transport works amazingly especially if you consider that its in its first 15 commits!

So, as I state in the title, sometimes starting a host, meaning making a server and client connection, fails.

#### I have this code:
```c#
private async Task<Lobby> CreateLobby()
    {
        try
        {
            const int maxPlayers = 8;

            // Create a relay allocation and generate a join code to share with the lobby
            var createdAllocation = await RelayService.Instance.CreateAllocationAsync(maxPlayers);

            var joinCode = await RelayService.Instance.GetJoinCodeAsync(createdAllocation.AllocationId);

            // Create a lobby, adding the relay join code to the Lobby data
            var options = new CreateLobbyOptions
            {
                Data = new Dictionary<string, DataObject>
                    { { JoinCodeKey, new DataObject(DataObject.VisibilityOptions.Public, joinCode) } },
                IsPrivate = true
            };

            var lobby = await Lobbies.Instance.CreateLobbyAsync("Lobby Name", maxPlayers, options);

            _transport.SetRelayServerData(new RelayServerData(createdAllocation, "dtls"));

            _networkManager.ServerManager.StartConnection();
            
            // wait for server to start
            while (!_networkManager.IsServer)
            {
                await Task.Delay(100);
            }
            
            JoinAllocation joinAllocation = await RelayService.Instance.JoinAllocationAsync(joinCode);  
            _transport.SetRelayServerData(new RelayServerData(joinAllocation, "dtls"));  

            _networkManager.ClientManager.StartConnection();
            
            var maxAttempts = 300;
            
            // wait for client to start
            while (!_networkManager.IsClient && maxAttempts-- > 0)
            {
                print ("Waiting for client to start");
                await Task.Delay(100);
            }
            
            return lobby;
        }
        catch (Exception e)
        {
            Debug.LogFormat($"CreateLobby Error {e}");
            return null;
        }
    }
```

So, I'm waiting for the _networkManager.IsClient to be true to continue.

In the cases when the connection is successfull, the "Waiting for client to start" gets logged ~30 times (at most), meaning after 30*100 = 3000ms. (Stating that just for general info :p), and then it passes the while loop.
    
When it fails, well, it just never stops waiting.

Right now the percentage of passing the while loop *feels like* 60%.
    
## I checked and verified:
- in StartConnection the "bool succeeded" (line 39) is true even when the LocalConnection is not Started (Meaning IsClient != true).
- in ClientBindAndConnect after line 66 the _connection.IsCreated is true even when the LocalConnection is not Started.
- in IterateIncoming it passes line 112 BUT it never gets into the "while incomingEvent", so it never gets to NetworkEvent.Type.Connect in the switch.
    
So, the NetworkEvent.Type.Connect incomingEvent is never emitted for some reason.

Thanks for your time, hope I helped :]

**Comment by ooonush** [comment]
Thanks for the interest in transport! I tried to reproduce the error, but it didn't work for me. I created a test MonoBehaviour, and in Start() I call CreateLobby(). Can you give me another hint where you call CreateLobby() from?

**Comment by zalkanorr** [comment]
Yeah of course!

First of all I forgot to mention my specs (which now that I think about may be the case why you couldn't reproduce?)
I'm on Unity 2021.3.21f1 <Metal> 
Macbook Pro M1 2020 Ventura 13.1

Maybe the M1, for some reason, has a different behavior?

The logic on which I call the CreateLobby is:
- A MonoBehavior script called Matchmaking
- It's a Singleton, here's the minimal version of its Start():
```c#
private void Start()
{
    DontDestroyOnLoad(gameObject);

    if (Instance == null)
    {
        Instance = this;
    }
    else
    {
        Destroy(gameObject);
    }
        
    _networkManager = FindObjectOfType<NetworkManager>();
    _transport = (FishyUnityTransport)_networkManager.TransportManager.Transport;
}
```
- I call Matchmaking.CreateNewLobby() from a button hook. here's CreateNewLobby()
```c#
public async void CreateNewLobby()
{
    status.text = "Connecting";

    await Authenticate();

    status.text = "Creating Lobby";

    ConnectedLobby = await CreateLobby();

    if (ConnectedLobby == null) return;

   // .... continue logic, the code doesn't reach this part when it fails
}
```
- And here is the Authenticate():
```c#
private async Task Authenticate()
{
    if (isLocal) return;
    if (isAuthenticated) return;

    try
    {
        var options = new InitializationOptions();

#if UNITY_EDITOR
        options.SetProfile(ClonesManager.IsClone() ? ClonesManager.GetArgument() : "Primary");
#else 
        if (DevelopmentMode == true) {
            var randomInt = UnityEngine.Random.Range(0, 100000);

            options.SetProfile($"NotPrimary{randomInt.ToString()}");
        }
#endif

        await UnityServices.InitializeAsync(options);

        await AuthenticationService.Instance.SignInAnonymouslyAsync();

        _playerId = AuthenticationService.Instance.PlayerId;

        isAuthenticated = true;
    }
    catch (AuthenticationException e)
    {
        print($"Authenticate {e}");
        // if is signed in, then return
        if (e.ErrorCode == AuthenticationErrorCodes.ClientInvalidUserState)
        {
            if (AuthenticationService.Instance.IsSignedIn)
            {
                _playerId = AuthenticationService.Instance.PlayerId;
                isAuthenticated = true;
            }
        }
    }
}
```

That's all the logic. Hope it's helpful!

**Comment by zalkanorr** [comment]
I got a major hint I think.

I observed that it always fails for me when the connected region is NOT europe-west4.
If its anything else than that, for example, europe-west2, then it fails.

Now I'm unsure if this is related with FishyUnityTransport or Unity Relay config or something.

**Comment by ooonush** [comment]
I'm working on a new version where I reworked a lot of things and I think this bug should be solved. As soon as I am sure that the transport works, I will post the new version.

**Comment by zalkanorr** [comment]
Perfect! Feel free to hit me up incase you want me to test anything, I'd be more than happy to help :]

**Comment by ooonush** [comment]
Hey, I released a new [pre-release version](https://github.com/ooonush/FishyUnityTransport/releases/tag/0.1.0a) of the transport. You can try the update and see if the bug is gone or not.😁

**Comment by SzczepanskiPiotr** [comment]
@ooonush What version of Unity Transport 2.0 is supported?

**Comment by SzczepanskiPiotr** [comment]
@ooonush Ok, I tried with newest 2.0.0-pre.8 and had issues with DataStreamReader and DataStreamWriter. These structss doesn't seem to have .readBytes and writeBytes with methods that accept two arguments. I needed to use readBytesUnsafe and writeBytesUnsafe. It is like this in Unity Netcode for Gameobject too for UTP 2.0 :)

**Comment by ooonush** [comment]
I have completed support for UnityTransport 2.0. You can try it in [FishyUnityTransport 0.2.0](https://github.com/ooonush/FishyUnityTransport/releases/tag/0.2.0).

**Comment by zalkanorr** [comment]
The new version fixed this issue completely! Thanks :]
