### ISSUE TITLE
A flaw in connecting to the host

### ISSUE THREAD

**Issue by ooonush** [ooonush/FishyUnityTransport#4]
When connected as a host, the data is still sent to the Relay server and comes back to the host.

**Comment by matt-seaton** [comment]
Could this be due to doing a joinallocation as host?  That's how your example code looks.  According to unity this should be done on remote client only.

**Comment by ooonush** [comment]
Yes, that's what it has to do with it, but I'll leave it at that. I already have a couple of ideas on how to solve this without changing the API.

**Comment by ooonush** [comment]
Resolved in `1.0.0.pre-1`.
